In [1]:
import numpy as np

phi = np.zeros((8, 8))
idx = 0
for dz in [-1, 1]:
    for dy in [-1, 1]:
        for dx in [-1, 1]:
            phi[idx] = [dx*dy*dz, dx*dy, dy*dz, dx*dz, dx, dy, dz, 1]
            idx += 1
   
dz = -1
dy = -1 
dx = 1
normal = np.array([-1, 0, 0])
phi[1] = [
    normal.dot([dy*dz, dx*dy, dy*dz]),
    normal.dot([dy, dx, 0]),
    normal.dot([0, dz, dy]),
    normal.dot([dz, 0, dx]),
    normal.dot([1, 0, 0]),
    normal.dot([0, 1, 0]),
    normal.dot([0, 0, 1]),
    0
]

print(phi)

inv_phi = np.linalg.inv(phi)

print(inv_phi)
b = np.array([0, 1, 0, 0, 0, 0, 0, 0])

r = np.array([-0.000001, -1.000000, -1.000000])
phi_r = np.array([r[0]*r[1]*r[2], r[0]*r[1], r[1]*r[2], r[0]*r[2], r[0], r[1], r[2], 1])
c = inv_phi.dot(b)
print(c)
print(phi_r)
print(inv_phi.T.dot(phi_r).dot(b))
print(phi_r.dot(inv_phi.dot(b)))

[[-1.  1.  1.  1. -1. -1. -1.  1.]
 [-1.  1.  0.  1. -1.  0.  0.  0.]
 [ 1. -1. -1.  1. -1.  1. -1.  1.]
 [-1.  1. -1. -1.  1.  1. -1.  1.]
 [ 1.  1. -1. -1. -1. -1.  1.  1.]
 [-1. -1. -1.  1.  1. -1.  1.  1.]
 [-1. -1.  1. -1. -1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]]
[[-0.    -0.25   0.125 -0.125  0.125 -0.125 -0.125  0.125]
 [ 0.     0.25  -0.125  0.125  0.125 -0.125 -0.125  0.125]
 [ 0.25  -0.25  -0.125 -0.125 -0.125 -0.125  0.125  0.125]
 [ 0.     0.25   0.125 -0.125 -0.125  0.125 -0.125  0.125]
 [-0.    -0.25  -0.125  0.125 -0.125  0.125 -0.125  0.125]
 [-0.25   0.25   0.125  0.125 -0.125 -0.125  0.125  0.125]
 [-0.25   0.25  -0.125 -0.125  0.125  0.125  0.125  0.125]
 [ 0.25  -0.25   0.125  0.125  0.125  0.125  0.125  0.125]]
[-0.25  0.25 -0.25  0.25 -0.25  0.25  0.25 -0.25]
[-1.e-06  1.e-06  1.e+00  1.e-06 -1.e-06 -1.e+00 -1.e+00  1.e+00]
-0.999999
-0.999999


In [2]:
import numpy as np
values = []
rows = []
cols = []
with open('matrix.txt') as f:
    lines = f.readlines()
    i = 0
    while len(lines[i]) > 3:
        _, v = lines[i].split(':')
        i += 1
        values.append(float(v))
    i += 1
    while len(lines[i]) > 3:
        _, v = lines[i].split(':')
        i += 1
        rows.append(int(v))
    i += 1
    while i < len(lines) and len(lines[i]) > 3:
        _, v = lines[i].split(':')
        i += 1
        cols.append(int(v))

print(len(values))
print(len(rows))
print(len(cols))

216
145
216


In [7]:
from scipy.sparse import csr_matrix
matrix = csr_matrix((values, cols, rows), shape=(len(rows) - 1, len(rows) - 1)).toarray()
for i in range(len(rows) - 1):
    line = matrix[i]
    if (matrix[i,i] != 1):
        print(i, ":", line)
    if (np.abs(line).sum() > 2):
        print(i, ":", line)
print(matrix[:4])

[[ 1.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.        

In [4]:
# invert the matrix
matrix = np.linalg.inv(matrix)
matrix

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [5]:
# LU decomposition
import scipy
from scipy.linalg import lu
P, L, U = lu(matrix)
print(P.shape)
print(L)
print(U)

(144, 144)
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
