In [4]:
import numpy as np

A = np.array(
    [
        [1, 2, 3],
        [2, 4, 5],
        [7, 8, 9],
    ]
)
u, s, vh = np.linalg.svd(A)
print(u)
print(s)
print(vh)

print("inverse of A")
print(np.linalg.inv(A))

[[-0.2301501  -0.51801074 -0.82382996]
 [-0.41759775 -0.71207959  0.56440657]
 [-0.87900117  0.47392777 -0.05243493]]
[15.82163215  1.61897756  0.23423896]
[[-0.45623319 -0.57912486 -0.67562243]
 [ 0.84950185 -0.05739285 -0.52445464]
 [-0.26494883  0.81321612 -0.51815216]]
inverse of A
[[ 0.66666667 -1.          0.33333333]
 [-2.83333333  2.         -0.16666667]
 [ 2.         -1.          0.        ]]
